apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend-deployment
  namespace: {{ .Values.namespace }}

spec:
  replicas: {{ .Values.backend.replicaCount }}

  revisionHistoryLimit: {{ .Values.backend.revisionHistoryLimit }}

  strategy:
    type: {{ .Values.backend.strategy.type }}

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:

      imagePullSecrets:
{{- toYaml .Values.backend.imagePullSecrets | nindent 8 }}

      containers:

        - name: backend

          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"

          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.backend.service.targetPort }}

          resources:
{{ toYaml .Values.backend.resources | nindent 12 }}