services:
  # 1️ MongoDB service
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: todo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 2️ Backend service (Node.js)
  backend:
    build:
      context: ./backend
      
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    environment:
      MONGO_CONN_STR: mongodb://admin:password@mongodb:27017/todo
      USE_DB_AUTH: "true"
    ports:
      -  "8081:8080" 
    depends_on:
      - mongodb
    networks:
      - app-network
    healthcheck: 
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      
      interval: 10s
      timeout: 5s
      retries: 5

  # 3️ Frontend service (React + Nginx)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - "3000:80" 
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge